In [26]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer, MissingIndicator

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [27]:
df = pd.read_csv(r"E:\Jupyter Notebooks\train.csv",usecols=['Age','Fare','Survived'])


In [28]:
df.tail()

Survived   Age   Fare
886         0  27.0  13.00
887         1  19.0  30.00
888         0   NaN  23.45
889         1  26.0  30.00
890         0  32.0   7.75

In [29]:
df.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

### fitting model after imputing missing values with mean

In [30]:
xtrain, xtest, ytrain, ytest = train_test_split(df.drop(['Survived'], axis=1),df['Survived']
                                               ,test_size=0.2, random_state=2)

In [31]:
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((712, 2), (179, 2), (712,), (179,))

In [32]:
si = SimpleImputer()
xtraint = si.fit_transform(xtrain)

In [33]:
xtraint

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [34]:
xtestt = si.transform(xtest)

In [35]:
clf = LogisticRegression()
clf.fit(xtraint, ytrain)
pred1 = clf.predict(xtestt)


In [36]:
accuracy_score(ytest,pred1)

0.6145251396648045

### fitting model after creating missing indicator column

In [37]:
xtrain, xtest, ytrain, ytest = train_test_split(df.drop(['Survived'], axis=1),df['Survived']
                                               ,test_size=0.2, random_state=2)

In [38]:
mi = MissingIndicator()
mi.fit(xtrain)

MissingIndicator()

In [39]:
mi.features_

array([0], dtype=int64)

In [40]:
xtraint = mi.transform(xtrain)
xtestt = mi.transform(xtest)

In [41]:
xtraint

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [42]:
xtestt

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [43]:
xtrain['ageNA']= xtraint

In [44]:
xtrain

Age      Fare  ageNA
30   40.0   27.7208  False
10    4.0   16.7000  False
873  47.0    9.0000  False
182   9.0   31.3875  False
876  20.0    9.8458  False
..    ...       ...    ...
534  30.0    8.6625  False
584   NaN    8.7125   True
493  71.0   49.5042  False
527   NaN  221.7792   True
168   NaN   25.9250   True

[712 rows x 3 columns]

 the missing indicator column indicates with its true false values whether a particular value was missing - true or not - false

In [45]:
xtest['ageNA'] = xtestt

In [46]:
xtest

Age     Fare  ageNA
707  42.0  26.2875  False
37   21.0   8.0500  False
615  24.0  65.0000  False
169  28.0  56.4958  False
68   17.0   7.9250  False
..    ...      ...    ...
89   24.0   8.0500  False
80   22.0   9.0000  False
846   NaN  69.5500   True
870  26.0   7.8958  False
251  29.0  10.4625  False

[179 rows x 3 columns]

In [47]:
xtraint

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [48]:
xtestt

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [49]:
si = SimpleImputer()
si.fit(xtrain)
trainx = si.transform(xtrain)
testx = si.transform(xtest)

In [50]:
clf = LogisticRegression()
clf.fit(trainx, ytrain)
pred = clf.predict(testx)
accuracy_score(ytest,pred)

0.6312849162011173

In [142]:
xtrain

Age      Fare  ageNA 
30   40.0   27.7208   False
10    4.0   16.7000   False
873  47.0    9.0000   False
182   9.0   31.3875   False
876  20.0    9.8458   False
..    ...       ...     ...
534  30.0    8.6625   False
584   NaN    8.7125    True
493  71.0   49.5042   False
527   NaN  221.7792    True
168   NaN   25.9250    True

[712 rows x 3 columns]

### using simple imputer class itself to create missing indicator

In [143]:
xtrain, xtest, ytrain, ytest = train_test_split(df.drop(['Survived'], axis=1),df['Survived']
                                               ,test_size=0.2, random_state=2)

In [144]:
si = SimpleImputer(add_indicator=True)
si.fit(xtrain)
xtraint = si.transform(xtrain)
xtestt = si.transform(xtest)

In [145]:
xtrain.columns.intersection(xtest.columns)

Index(['Age', 'Fare'], dtype='object')

In [146]:
xtrain.columns

Index(['Age', 'Fare'], dtype='object')

In [147]:
xtest.columns

Index(['Age', 'Fare'], dtype='object')

In [148]:
xtraint

array([[ 40.        ,  27.7208    ,   0.        ],
       [  4.        ,  16.7       ,   0.        ],
       [ 47.        ,   9.        ,   0.        ],
       ...,
       [ 71.        ,  49.5042    ,   0.        ],
       [ 29.78590426, 221.7792    ,   1.        ],
       [ 29.78590426,  25.925     ,   1.        ]])

In [149]:
clf.fit(xtraint, ytrain)
pred = clf.predict(xtestt)
accuracy_score(ytest, pred)

0.6312849162011173