In [45]:
from sklearn.datasets import load_diabetes
import numpy as np

In [7]:
x,y = load_diabetes(return_X_y = True) # y default loads scaled data

In [9]:
x.shape

(442, 10)

In [10]:
y.shape

(442,)

In [12]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=4)

In [13]:
from sklearn.linear_model import Ridge

r = Ridge(alpha = 0.1, solver = 'cholesky') # this solver uses ols not gd to solve coef values
r.fit(xtrain,ytrain)
r.coef_, r.intercept_

(array([  44.02063391, -241.69329987,  452.98665299,  332.04420177,
         -76.33686744,  -68.52143809, -164.98809083,  149.96908118,
         431.61347417,   58.51862681]),
 150.89053425602808)

In [19]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.identity(xtrain.shape[1])

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.insert(xtrain, )

In [28]:
xtrain.T.shape, xtrain.shape # this upon dot product gives a matrix of shape 10,10 so we can easily add it to the lambda W term
#  

((10, 353), (353, 10))

In [29]:
np.dot(xtrain.T, xtrain).shape

(10, 10)

In [43]:
class MeraRidge :
    
    def __init__(self, alpha = 0.1):
        self.alpha = alpha
        self.coef_ = 0
        self.intercept_ = 0
        
        
    def fit(self, xtrain, ytrain):
        xtrain = np.insert(xtrain, 0, 1, axis = 1)
        identity = np.identity(xtrain.shape[1])
        identity[0][0] = 0 #done since the solver of Ridge class uses this
        calculations = np.linalg.inv(np.dot(xtrain.T, xtrain) + self.alpha * identity).dot(xtrain.T).dot(ytrain)
        self.coef_ = calculations[1:]
        self.intercept_ = calculations[0]
        
        

In [44]:
meraR = MeraRidge()
meraR.fit(xtrain,ytrain)
meraR.intercept_, meraR.coef_

(150.89053425602813,
 array([  44.02063391, -241.69329987,  452.98665299,  332.04420177,
         -76.33686744,  -68.52143809, -164.98809083,  149.96908118,
         431.61347417,   58.51862681]))

In [37]:
np.insert(xtrain, 0, 0, axis = 1)

array([[ 0.        ,  0.0090156 , -0.04464164, ...,  0.02323852,
         0.05568623,  0.10661708],
       [ 0.        ,  0.03081083,  0.05068012, ...,  0.05755657,
         0.0354587 ,  0.08590655],
       [ 0.        ,  0.01628068, -0.04464164, ..., -0.03949338,
        -0.05947118, -0.06735141],
       ...,
       [ 0.        ,  0.04170844,  0.05068012, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [ 0.        ,  0.01628068,  0.05068012, ..., -0.03949338,
         0.01703607,  0.00720652],
       [ 0.        ,  0.04897352,  0.05068012, ...,  0.07120998,
         0.03243232,  0.04862759]])